"""add idempotency_key to events

Revision ID: 03d04b7773ef
Revises: f564ffdaf3f2
Create Date: 2026-05-14 09:48:42.313116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03d04b7773ef'
down_revision: Union[str, Sequence[str], None] = 'f564ffdaf3f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'events', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='unique')
    op.drop_column('events', 'idempotency_key')
    # ### end Alembic commands ###
