"""remove_fk_from_delivery_attempts_&_unq_contraint_from_events

Revision ID: 7680c3b182e6
Revises: fdd60fbee49e
Create Date: 2026-06-17 05:30:19.889562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7680c3b182e6'
down_revision: Union[str, Sequence[str], None] = 'fdd60fbee49e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_delivery_attempts_event_id'), 'delivery_attempts', ['event_id'], unique=False)
    op.drop_constraint(op.f('delivery_attempts_event_id_fkey'), 'delivery_attempts', type_='foreignkey')
    op.drop_constraint(op.f('events_idempotency_key_key'), 'events', type_='unique')
    op.create_unique_constraint('uq_tenant_idempotency', 'events', ['tenant_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tenant_idempotency', 'events', type_='unique')
    op.create_unique_constraint(op.f('events_idempotency_key_key'), 'events', ['idempotency_key'], postgresql_nulls_not_distinct=False)
    op.create_foreign_key(op.f('delivery_attempts_event_id_fkey'), 'delivery_attempts', 'events', ['event_id'], ['id'])
    op.drop_index(op.f('ix_delivery_attempts_event_id'), table_name='delivery_attempts')
    # ### end Alembic commands ###
