"""add_trace_id_to_events

Revision ID: b2dca914ee31
Revises: 8603e8d422c5
Create Date: 2026-06-05 03:33:21.877226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2dca914ee31'
down_revision: Union[str, Sequence[str], None] = '8603e8d422c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('trace_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_events_trace_id'), 'events', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_trace_id'), table_name='events')
    op.drop_column('events', 'trace_id')
    # ### end Alembic commands ###
