"""add retry columns to events

Revision ID: f564ffdaf3f2
Revises: 
Create Date: 2026-05-12 12:33:39.931588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f564ffdaf3f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('events', sa.Column('attempt_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'attempt_count')
    op.drop_column('events', 'next_retry_at')
    # ### end Alembic commands ###
